### ISSUE TITLE
grid.get_token_pos() doesn't work

### ISSUE THREAD

**Issue by jakobzmrzlikar** [mucamaca/gravity_connect#12]
it should return the position where a token placed at coordinates specified by arguments x and y would end its path through the grid, however, it just returns (x,y).

Maybe all Tile states are incorrectly set to special? because all, apart from the central ones, are the same.

**Comment by mucamaca** [comment]
there are no special tiles. 
The tiles that were special in previous version are now the tiles with dir =  (0,0)

**Comment by mucamaca** [comment]
Fixed in c24f8457a601e65a9e084dde2d85d2f41abc6f12.
