### ISSUE TITLE
BLOCKED tiles have a colour problem

### ISSUE THREAD

**Issue by jakobzmrzlikar** [mucamaca/gravity_connect#17]
BLOCKED tiles change colour depending on how many players are playing. if num_of_players == 3, then BLOCKED tiles are coloured white, just like empty ones.

i recommend that we make BLOCKED tiles constant colour

**Comment by jakobzmrzlikar** [comment]
resolved with 54b3848b2f0b9b116836e642297405168e579d86 however it is an ugly fix.

It works for now, but I suggest that we make BLOCKED tile state have a constant number and not be dependent on the number of players

**Comment by mucamaca** [comment]
I reverted 54b3848b2f0b9b116836e642297405168e579d86 and fixed the bug that actually caused this in a92bc5cec5a254fa168c79b11d9990c1eea0f51c.
