### ISSUE TITLE
win detection doesn't work. AGAIN

### ISSUE THREAD

**Issue by jakobzmrzlikar** [mucamaca/gravity_connect#18]
in some cases, like the one below, win detection doesn't work for me.

<img width="1280" alt="2017-08-05" src="https://user-images.githubusercontent.com/13316867/28995615-bfb69030-79ed-11e7-9a3f-f9973d057c83.png">

fix ASAP so we can make the release

**Comment by mucamaca** [comment]
nice background

**Comment by mucamaca** [comment]
you can reopen old issues as well

**Comment by mucamaca** [comment]
Fixed in 8cfad1a7a49a55ab9c2ac65e1ff544edf5ff87d1.

**Comment by mucamaca** [comment]
you can build the release now, I believe

**Comment by mucamaca** [comment]
this is so annoying

**Comment by mucamaca** [comment]
Fixed with 64b6c73ffa54607a5e3c6e61bcb482060205f583. I hope  this is the last time i had to do this

**Comment by mucamaca** [comment]
nope, it still doesn't work.

**Comment by mucamaca** [comment]
fixed it once again in d195a854e002dd8752e05c7ce12a344ef575ed46.
@jakobzmrzlikar can you build new binaries for another minor release?
