### ISSUE TITLE
rewrite falling animation

### ISSUE THREAD

**Issue by mucamaca** [mucamaca/gravity_connect#3]
jaz zdaj pišem ai in sem ugotovil, da je to praktično nemogoče združit z animacijo v stanju, kot je zdaj.
Mislim, da bi jo blo treba spisat čist na novo. Predlagam, da nardiš nekako tako, da ma GUI class svoj lasten grid, ki se ob pravem času kopira iz tistega grida v Coru. 
Pa ko boš delal branchaj ai v nekaj svojega pa tam delaj, da bom lahko jaz vzporedno delal na AIju

**Comment by jakobzmrzlikar** [comment]
this should now be fixed with commit 49cd97ee2708063da6cad1c883804b253a1c7d8d

**Comment by jakobzmrzlikar** [comment]
by now, GUI is fully rewritten, fully functional and supports arbitrary number of players, along with AI
