### ISSUE TITLE
on branch 0.1.x: adding new tokens is not blocked when a token is falling

### ISSUE THREAD

**Issue by mucamaca** [mucamaca/gravity_connect#5]
Clicking quickly on the same valid field in grid results in a weird glitch where center fields can get colored and multiple game over dialogs appear and then refuse to get closed. I think it has something to do with the mutlithreaded token insertion.

**Comment by mucamaca** [comment]
We have to fix this before the new release

**Comment by jakobzmrzlikar** [comment]
ok, I'll take a look at it ASAP

**Comment by jakobzmrzlikar** [comment]
the last commit should fix the issue
