### ISSUE TITLE
core.insert_token doesn't seem compatible with GUI

### ISSUE THREAD

**Issue by jakobzmrzlikar** [mucamaca/gravity_connect#7]
I've found a design problem with our methods. The problem is that GUI needs to know if a tile can be put on (x,y) BEFORE it is actually put there. 

In other words, the program currently does insert_token(x, y) and if that returns True, it continues to animate the token drop. however, while the token is dropping, the screen gets constantly refreshed, which means that, because token is already inserted in the grid, it's gonna be shown there before it's animation actually falls down. 

Please give this a thought. Should we make another method that just checks if the token can be placed there?

**Comment by mucamaca** [comment]
I think I fixed it.

**Comment by mucamaca** [comment]
The methods in core.py are documented now as well.

**Comment by jakobzmrzlikar** [comment]
ok, I think this should be compatible now
