### ISSUE TITLE
problem with Tile class

### ISSUE THREAD

**Issue by jakobzmrzlikar** [mucamaca/gravity_connect#9]
if I run the program, the GUI works (never mind the incorrect colours), but if I click on any tile, it throws:

Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1553, in __call__
    return self.func(*args)
  File "GUI.py", line 68, in mouse_click
    self.place_token(mouse_x, mouse_y)
  File "GUI.py", line 112, in place_token
    self.drop_token(x, y, pos)
  File "GUI.py", line 84, in drop_token
    if (x, y) != pos:
  File "/media/work/Projects/gravity-connect/src/tile.py", line 19, in __eq__
    return self.state == other.state
AttributeError: 'tuple' object has no attribute 'state'

please fix ASAP

**Comment by jakobzmrzlikar** [comment]
se mal sem si pogledal in sem ugotovil, da grid.get_token_pos(x,y) vrne Tile object. A je to namenoma al je napaka? Ker bi blo velik bols ce bi vrnu samo 2-tuple koordinat.

**Comment by jakobzmrzlikar** [comment]
nvm sem ze resu, problem je bil da nism mogu equatat tupla in Tile objecta, zato sem vmes zdej pretvoril Tile object v tuple in zdej dela.

**Comment by mucamaca** [comment]
Ok, i just wanted to explain that.

**Comment by mucamaca** [comment]
I think you forgot to push the fix

**Comment by jakobzmrzlikar** [comment]
yeah incoming, stay tuned cuz there's another problem in config

**Comment by jakobzmrzlikar** [comment]
yeah incoming, stay tuned cuz there's another problem in config
